### PR TITLE
Add component gridHelper

### PR DESCRIPTION
**Pull request by pepjo**
I'm filling the pull request but there are actually 3 things I'm missing:

- Cannot complete documentation. I modified the internalComponentCategories but gridHelper.js does not create after runnig `gulp doc`
- I don't know what tests should I write :/
- The component does not work, ups :sweat_smile:. When I try to mount it I get 
````
2(index):1 [.CommandBufferContext]RENDER WARNING: Render count or primcount is 0.
````

I hope you can give me some orientation on these and I'll fix the request

### CODE REVIEW

**Comment by toxicFork** [comment]
Hi, thanks a lot for opening up the PR :D I'll help with the issues you're having :)

**Comment by toxicFork** [comment]
Okay after taking a look, the changes on `staging/2.0` make `gulp doc` work now!

```bash
git checkout -b pepjo-components/grid-helper/add staging/2.0
git pull https://github.com/pepjo/react-three-renderer.git components/grid-helper/add
gulp doc
```

Looking at tests, I would start by checking if the current tests are not broken ( they should not be ).

I'm looking at the error you mentioned above now :)

**Comment by pepjo** [comment]
Ok! Thanks, I'll look into it this next week :)

**Comment by toxicFork** [comment]
I'm sorting these out now that I have more time :D

**Comment by Colmea** [comment]
/!\ Since Three.js r79,  **step** property is now **divisions** ([See r79 release changelog](https://github.com/mrdoob/three.js/releases/tag/r79)).

I don't know if r3r 2.3.2 should support only r79 and higher versions ?

**Pull request merged**
