### PR TITLE
Sprite descriptor

### PR DESCRIPTION
**Pull request by robertlong**

### CODE REVIEW

**Comment by toxicFork** [comment]
Thanks for the PR! :D

**Comment by robertlong** [comment]
Yeah no problem! Should those of us who want to help out keep going down the list in #2 ?

I'm currently using three.js inside a React app and would eventually want to rip it out and replace it with this. Let me know what I can do to help.

**Comment by toxicFork** [comment]
Ah sorry just saw the reply... yes #2 is a good place to start :) The rest is still a bit complex but I will make it easier to improve, I may need some help with docs for example but since it's a submodule it will be harder to do PRs for that, but I'll sort that out soon as well.

**Comment by toxicFork** [comment]
PR looks good, merging and adding contribs now

**Pull request merged**
