### PR TITLE
add missing `map` property in pointsMaterial

### PR DESCRIPTION
**Pull request by alexkuz**

### CODE REVIEW

**Comment by toxicFork** [comment]
Thanks for the PR, FYI the travis failure is a server issue and Travis team is fixing that one so don't worry about it, there are a couple things I will need to do to make sure it's compatible with other ways of setting map as well

**Comment by toxicFork** [comment]
Hi @alexkuz , I have considered this option but decided to go with placing the texture "the react way" instead, see https://github.com/toxicFork/react-three-renderer/wiki/pointsMaterial#notes

**Comment by alexkuz** [comment]
@toxicFork ok, thanks!
BTW, I've made a few other changes to make [stellar-webpack](https://alexkuz.github.io/stellar-webpack/) render properly, you might want to take a look (I've added `bufferGeometry` and some missing props):

https://github.com/toxicFork/react-three-renderer/compare/master...alexkuz:@alexkuz?expand=1

**Comment by toxicFork** [comment]
Cool I will be able to check it out tomorrow evening gmt :D

**Pull request closed without merging**
