### PR TITLE
Adding RawShaderMaterial descriptor

### PR DESCRIPTION
**Pull request by DelvarWorld**

### CODE REVIEW

**Comment by DelvarWorld** [comment]
Actually I don't think this should extend materialdescriptorbase. Maybe it shouldn't extend anything?

**Comment by toxicFork** [comment]
Yes I think you can extend `THREEElementDescriptor`. I will add tests to see whether uniforms will work with this or not, but I think they should.

**Comment by DelvarWorld** [comment]
amended commit extending `THREEElementDescriptor`

**Comment by DelvarWorld** [comment]
Also are there any considerations with `<materialResource resourceId={} />` here? Does `<shaderMaterial />` already work here?

**Comment by DelvarWorld** [comment]
amended to remove `hasWireframe()` call in raw constructor

**Comment by DelvarWorld** [comment]
Although now `getMaterialDescription()` won't be there - I think I'm not yet well enough versed in this project to make this change confidently ;)

**Comment by toxicFork** [comment]
Hmm yes just realized a problem... May be better to extend shadermaterial
actually... Don't worry I'll do the necessary changes before merging, will
show you the changes to explain why :)

**Comment by toxicFork** [comment]
I have just looked at it further, looks like RawShaderMaterial is very very similar to ShaderMaterial, except it just doesn't add any prefixes to the vertex/fragment shaders. So it's safe to just extend :D Merging now :)

**Comment by DelvarWorld** [comment]
ah ok, I wasn't sure if this mattered for inheriting the other methods, for example the wireframe stuff. I don't know how docs are generated, but if they include inheritance props then the docs would incorrectly say that "wireframe" is a property you can set, which would have no effect

**Comment by toxicFork** [comment]
Yes I will be improving a lot about generating docs, testing etc, it should be much easier to add things in soon. For now I created a little guide in #2 , I will put something like that in the wiki. Regarding `wireframe`, [it still works I think](https://github.com/mrdoob/three.js/blob/ddab1fda4fd1e21babf65aa454fc0fe15bfabc33/src/renderers/WebGLRenderer.js#L850), but some of the other props may not. we will need to add tests to see which ones we can remove. Once I cook the next release ( soon :D ) I will add some examples for the new stuff in the last release.

**Comment by toxicFork** [comment]
And https://github.com/toxicFork/react-three-renderer/commit/7952d837e42d34b2aeb620937357eb30619b6f5f is the actual commit for the minor fixes I did for RawShaderMaterial.

**Comment by toxicFork** [comment]
And why it needs to extend ShaderMaterial:

- Currently MaterialDescriptorBase includes the logic to assign itself to a mesh when mounted.
- Additionally, it marks itself to be used as a resource
- ShaderMaterialDescriptor then permits uniform variables to be added within
- Also RawShaderMaterial itself extends ShaderMaterial in THREE.js

**Pull request merged**
