### PR TITLE
Alllow React v15

### PR DESCRIPTION
**Pull request by MoOx**
As there is no real breaking changes, this should be ok.

### CODE REVIEW

**Comment by toxicFork** [comment]
Thanks for the PR :D I am moving house this week but should be able to merge in the weekend :)

**Comment by MoOx** [comment]
The CI is broken, it seems you are using some private React stuff (react/lib/* is considered to be private). This will need more work.

**Comment by toxicFork** [comment]
Yes as react becomes more abstract and less DOM oriented I will need to use less from react/lib as at the moment I am essentially reimplementing parts of react DOM and borrowing other parts. I will take a look and fix :)

**Comment by toxicFork** [comment]
https://github.com/facebook/react/compare/v0.14.7...v15.0.0-rc.1 ow ow ow

**Comment by toxicFork** [comment]
Merging into branch https://github.com/toxicFork/react-three-renderer/tree/upgrade/react-15-compat

**Comment by toxicFork** [comment]
All done :D https://github.com/toxicFork/react-three-renderer/releases/tag/v2.0.0

**Pull request closed without merging**
